title: Jef Aldrich
email: jef@example.com
baseurl: ""
url: ""
markdown: kramdown
plugins: []

# Site settings
name: Jef Aldrich
role: Global IT & Cybersecurity Leader
certifications: "CISSP • CISM • OSCP"
location: ""
